version: '3.8'

services:
    api:
        build: .
        container_name: picts_manager_api

        ports:
            - '3000:3000'

        env_file:
            - .env
        volumes:
            - ./logs:/app/logs
            - ./uploads:/app/uploads
