name: Build and Deploy
on:
    workflow_run:
        workflows: ['Test and Lint']
        types:
            - completed
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            # - name: Connect to Server
            #   uses: appleboy/ssh-action@master
            #   with:
            #       host: ${{ secrets.HOST }}
            #       username: ${{ secrets.USERNAME }}
            #       key: ${{ secrets.SSH_KEY }}
            #       port: ${{ secrets.PORT }}
            #       script: |
            #           cd ${{ secrets.APP_PATH }}
            #           git pull
            #           docker compose up --build -d
